### ISSUE TITLE
General short term roadmap

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#1084]
These are from my notes that I discussed on Monday following DockerCon. Some of these have already resulted in opening new issues, but I'm publishing these here for now as an epic and we can continue to open related issues.

### general
 - [x] #1102: many of our commands don't accept multiple arguments (for example, many of the `rm` commands should be able to remove multiple resources, such as services at a time)

### amp (cli)
- [x] command to set (and preserve) default server, and other config options (like theme, verbose mode, etc), and display current config (as before)
- [x] restore configuration support
    - default config under home
    - local config (eg, ./.amp) for stack projects (directory with a stack file)
    - automatic version check to inform user when an updated version is available
    - cli should be able to display progress bars for lengthy operations, should be able update status lines in place

### signup and verification
- [ ] sms support
- [ ] #1100: multiple signup/verification strategies supported
- [x] #1088: should only be able to verify/activate once (currently can repeat, but should be a one-time use token with expiration)
- consider renaming verify -> activate
- consider automatic login after activation; otherwise, make it clearer to log in

### registry
Can potentially expose public repos for docker pull, use amp account / cli for pushing
- multi layer caching/mirroring
- push and pull from account registry
- set public permissions for registry
- list registry repos, tags

### stack
- [x] #1081: if don't supply stack name, default to the stackfile name
- [ ] should be able to publish public port for service at route
- [x] #1101: should be able to deploy a two-letter stack name ($ amp stack deploy -c stacks/visualizer.stack.yml ui)
- [ ] #1305 when publishing a compose file, the "default" network should result in a completely sealed off stack (ie, no public access; user must specify public network (e.g., public) should be used for publishing public service to publish a public service (we should probably use "public" or "frontend", not "ampnet" for this; I think "public" removes all ambiguity)
- [x] #1103: should be able to remove or update a stack by name or id fragments (and this should be generally true across all similar commands)
- [x] #1079: should be able to supply environment variables for stack creation
- [ ] we will still need to support non-DNS ways to access a stack (eg, via published ports)
- [x] need a way to inspect stack services
- [x] should be able to supply environment variables for stack creation
- [ ] deploy stack from private repo (ex, private Docker Hub repo)

### service
- [x] #1105: need to be able to inspect service status, details (eg, equivalent to docker service ls, docker service ps, docker service inspect). We need something like the following to restrict the service list to just a stack's services

    $ amp service ls  # list all services
    $ amp service ls --stack=foo --stack=bar  # only list services of foo and bar stacks
    $ amp service inspect xyz
    $ amp service ps xyz

### storage (file/block/object)
- [infinit](https://infinit.sh/)
- [minio](https://www.minio.io/)
- [rook](https://rook.io/)
- [storageos](https://storageos.com/)

### security
- [ ] #1058: TLS enabled for the amplifier service
- [ ] TLS for core services
- [ ] need to implement swarm secret support and managed via cli/ui

### Windows support
- [x] cli - amp is now fully supported on Docker for Windows
    - ~should not mount unix docker socket under windows~
    - ~should disable cluster commands (since these require access to docker socket)~

### Augment examples and documentation around various scenarios
(starter list):
- [ ] Create a cluster
- [ ] Update a cluster
- [ ] Create a swarm - allocate nodes and initialize swarm
- [ ] Share service between authorized stacks
- [ ] Perform rolling updates with automatic rollback when tests fail
