### ISSUE TITLE
Switch from Kafka to NATS Streaming

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#113]
Replace message queuing infrastructure with NATS streaming service. This will require:
- [ ] Updating agents that push messages to queue.
  - [x] ampagent (appcelerator/amp-agent#2)
  - [ ] telegrafagent (this should be done as a plugin)
- [ ] Updating workers that pull from the queue to update
  - [x] amplogworker (appcelerator/amp-log-worker#10)
  - [ ] telemetryworker
- [ ] rpc streaming service clients
  - [x] logs (appcelerator/amp#123)
  - [ ] stats

NATS streaming uses protocol buffers.

**Comment by subfuzion** [comment]
@bertrand-quenin is currently working on amp-log-worker.

**Comment by subfuzion** [comment]
@chrisccoy researched NATS and is following this issue https://github.com/influxdata/telegraf/pull/1697 for the telegraf -> NATS output plugin.

**Comment by subfuzion** [comment]
@bertrand-quenin @chrisccoy @ndegory @freignat91 As I mentioned on slack yesterday, I'm going to relax the requirement for file store for guaranteed delivery for the alpha. We can focus on that as part of our productionizing/hardening efforts subsequently. @ndegory If you have the bandwidth to research and evaluate, that's great, but it's not a priority for the moment.

**Comment by chrisccoy** [comment]
As a quick update, I confirmed that when using the image `appcelerator/nats-streaming:0.2` from `nats` branch, the basic client works with the streaming server without changes. I think @ndegory mentioned this was possible today in the sync, but I was able to confirm. The streaming server embeds the core server, so it works like a charm:
https://github.com/nats-io/nats-streaming-server#running

I am going to start working on integrating the strategy with `telegrafagent` and `telemetryworker`

**Comment by chrisccoy** [comment]
Next steps are to integrate with influxdb, but, so far, NATS producer and consumer are working with telegraf, which is encouraging.

**Comment by bquenin** [comment]
Nats prototype for logging is done. Instruction on how to test is available in #123 PR.

**Comment by subfuzion** [comment]
I mentioned that I was willing to relax the requirement for guaranteed delivery for now [above](https://github.com/appcelerator/amp/issues/113#issuecomment-244138687) (although I wasn't expecting pathological behavior) as noted [here](https://github.com/appcelerator/amp/issues/141).

I have multiple concerns. One is that I didn't want to _increase_ operational complexity with multiple message streaming solutions; I wanted to settle on on one. Another is NATS relative maturity; I initially selected Kafka because it is obviously the battle-tested and hardened solution and it was designed from the onset with a strong clustering model (another concern is that NATS Streaming doesn't support clustering yet (see [here](https://groups.google.com/forum/#!topic/natsio/gkbi7Nm4iTk)) as well as extremely high throughput event log streaming and strong message ordering guarantees (effectively at-least-once delivery [by default](http://kafka.apache.org/documentation.html#semantics)).

If we are going to evaluate NATS against Kafka, it needs to be NATS Streaming, and we will have to configure message acknowledgements to match Kafka's default (see NAT Streaming [at-least-once-delivery](http://nats.io/documentation/streaming/nats-streaming-intro/#features:e3e06e7d6a5a7f6a8f8acec7f42f38c0)).

**Comment by subfuzion** [comment]
I just quickly glanced at the NATS client, but it seems like we would have implement our own logic around write acknowledgements?

https://github.com/nats-io/nats/blob/master/nats.go#L1696
https://github.com/nats-io/nats/blob/master/nats.go#L190
https://github.com/nats-io/nats/blob/master/nats.go#L561
https://github.com/nats-io/nats/blob/master/nats.go#L1321-L1335

Is there no option to just set messaging modes, like `at-least-once` delivery and let the client deal with the logic? bleah  😦

**Comment by bquenin** [comment]
We decided to revert to Kafka for the time being.
