### ISSUE TITLE
Core AMP stack deployment

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1544]
Whether on a cloud swarm cluster or on a local manager node, deployment of the AMP core services.
- [x] #1545 - single instance or cluster mode for Elasticsearch and etcd
- [x] #1546 - environment variables in core stack files
- [ ] #1169 - certificate management
- [x] #1446 - check system requirements before deployment
