### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1688]
There are a few tasks that need to be taken care of in order to reduce our technical debt:

- [x] #1689 Update vendors to use official Docker SDK
- [x] #1690 Use dep as vendoring tool
- [x] #1691 Reintegrate `cluster` binaries to top-level project
- [x] #1692 Update `gotools` and `amptools` images to use fixed versions
- [ ] #1699 Update missing/incomplete documentation
- [ ] #1701 Consolidate AWS plugin source under `cluster/plugin/aws`
- [x] #1702 Move CLI tests along with other tests in `tests` directory
- [x] #1712 Remove dead code from platform folder
- [x] #1713 Remove cmd/ampwrapper
- [x] #1714  Remove dead code from hack folder
